### ISSUE TITLE
UI not visible

### ISSUE THREAD

**Issue by Oinosseus** [dchoptiany/lmpgui#2]
For an unknown reason I cannot see the LMP GUI UI.
After I click it, it shows up. But when I click it, the SpeedInMph and IndicatorsOn button events do fire and so they change theior value.

The image shows the remeining artifacts from the UI:
![grafik](https://user-images.githubusercontent.com/9088147/198739241-7321407c-8f4c-422a-830a-322b314b1d86.png)

**Comment by dchoptiany** [comment]
Thank you very much for creating this issue! In the nearest future I will check out your pull request :)
